### ISSUE TITLE
No Connection message flashes and is removed without interaction

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#936] opened 2019-07-22 12:20 UTC
## Problem

When offline - User tried to login
No connection message with retry button appears - flashes and user is redirected to the userlogin page

## Solution
No connection message should remain until user interacts with screen - clicking on retry button

**Comment by vasildimitroffhristoff** [comment] 2019-07-25 07:38
Duplicate of #949

**Closed** 2019-07-25 07:38 UTC
Labels: bug

**Comment by Danman7** [comment] 2019-07-25 07:42
@stacylorraineprendeville This is heavily related to the duplicate issue and will be fixed with it.
