### ISSUE TITLE
Takes too long to log in

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#524] opened 2019-04-16 18:30 UTC
When I log in in the app, it takes too long to enter. It took me more than 3 minutes. I had good wifi.

![Screenshot_2019-04-16-14-30-01.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/8cac6900-a699-4287-a004-d4151c07b8da)

**Comment by Danman7** [comment] 2019-05-07 11:52
Duplicate of #551?

**Closed** 2019-05-07 19:09 UTC
Labels: bug, duplicate
