### ISSUE TITLE
Crash login when downloading maps

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#869] opened 2019-07-04 14:27 UTC
I logged in the app with 
demo/demo

1. the surveys and families finished downloading, but when it got to the maps section, this message appeared:

![Screenshot_2019-07-04-10-04-46.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5795544e-c275-42b0-8041-76dd3fbfd8ca)

2. Then I clicked on retry, and the downloading page appeared again, but the maps were downloading first and the surveys and images appeared as if it did not download.
![Screenshot_2019-07-04-10-17-51.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1de7e201-e5ae-4d3c-8767-8ea087837422)
![Screenshot_2019-07-04-10-14-06.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1ece4d3e-7630-4013-8141-a234b67dc90a)

3. When the downloading page was about to finish, the app crashed. 

4. Then, I clicked on the app again and the app was logged in and showing the dashboard.

**Comment by zommerberg** [comment] 2019-07-08 09:50
i could not reproduce this issue, could it be an internet connection problem?

**Comment by aprojas** [comment] 2019-07-11 20:04
This might have to do with the app crashing in old devices.. 
@zommerberg

**Comment by zommerberg** [comment] 2019-07-15 10:42
The issue with the app crashing on older devices was just fixed.

**Comment by aprojas** [comment] 2019-07-15 13:37
This keeps happening, and this time (I tried it on July 15) the "retry" button did not work, it just crashed automatically.

@zommerberg

**Comment by Danman7** [comment] 2019-07-16 12:42
There is something very wrong with old devices and our dependencies. We have now installed something called multiDex which helps with that. It's an ongoing configurational process. We have now found additional problems related to maps and have issues for them. We will keep this open to monitor.

**Comment by zommerberg** [comment] 2019-07-23 07:45
We have worked a lot on issues related to maps and loading.This should be fixed now.

**Closed by zommerberg** 2019-07-23 07:45 UTC
Labels: bug, question
