### ISSUE TITLE
Turning on Data results in Sync error.

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#144] opened 2018-12-08 19:14 UTC
**Describe the bug**
Sync Error after switching on data.

**To Reproduce**
1. Take a survey offline.
2. Turn on sync.
3. It directly shows me sync error.
4. I can't do ANYTHING to try it again (I think the network interface was not ready as it was way to fast with showing me the error.)

**Expected behavior**
Don't show an error. Or give me the possibility to sync again.

**Screenshots**
![screenshot_20181208-200946](https://user-images.githubusercontent.com/8961100/49689733-b68f3380-fb25-11e8-86e1-682ecd3b1209.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P10
- Android: 8

**Comment by IvaKop** [comment] 2018-12-09 14:52
@pA1nD closing as I cannot reproduce. If it happens again please reopen and describe steps.

**Closed by IvaKop** 2018-12-09 14:52 UTC
