### ISSUE TITLE
Tags not displaying all text

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#873] opened 2019-07-06 07:12 UTC
![Screen Shot 2019-07-06 at 09.11.40.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/77b22d1a-bf2c-4cda-a555-5def98a617ae)

**Comment by zommerberg** [comment] 2019-07-10 09:02
Witch tags? Could you give more info on the issue? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment] 2019-07-10 09:22
@zommerberg we only have one set of tags in the whole app - those related to the state of the lifemap
Draft, Sync pending, Sync error, completed
as is clear to see in the image above the text does not fit
it just says sync - this is an error that is causing clients confusion in reporting issues
The tag has to fit the text

**Comment by zommerberg** [comment] 2019-07-10 09:52
I cant reproduce it on phone and tablet.Is this still an issue? can we close it? @stacylorraineprendeville 
<img width="272" alt="Screenshot 2019-07-10 at 12 40 53" src="https://user-images.githubusercontent.com/43446836/60959817-8903a600-a311-11e9-9b4e-d72ca840b695.png">
<img width="454" alt="Screenshot 2019-07-10 at 12 51 11" src="https://user-images.githubusercontent.com/43446836/60959819-8903a600-a311-11e9-9644-e6686c0dd315.png">

**Comment by stacylorraineprendeville** [comment] 2019-07-10 10:52
@zommerberg yes it is an issue - please make the tags wider - this screen grab comes from a client who incorrectly told us they had sync errors that were in fact pending syncs - GECO - We lost hours and are still loosing hours in repairing this bug - If the tag was working on his device it would not have happened - Just because it is working on your device - does not mean it is working - please use the accessbility feature in your device and make the text larger - then check again - I think the issue is caused by using a fixed pixel width - we cannot control clients text size choice in their device but we must design for it to be increased

**Closed** 2019-07-16 12:20 UTC
Labels: bug
